### ISSUE TITLE
Record Watcher performance question

### ISSUE THREAD

**Issue by garrison-ball** [service-portal/CCW3956#1]
Hey! Thanks for offering an awesome class.

With the 'spRecordWatcher', what are the performance impacts?  Is it constantly polling the instance, or is new data somehow 'pushed' from SN?

**Comment by assertivist** [comment]
If i understand correctly, there is a constant "heartbeat" like request being sent via angular whenever there are updates. I believe it posts every few seconds when there is a "live" dependency like spRecordWatcher (it perhaps even does this manually in its code) and in those responses are when the updates are "pushed" to the client.

**Comment by garrison-ball** [comment]
Thank you!  Is there a place we can look up a list of similar functions?  I tried the googles, but they do nothing.

**Comment by assertivist** [comment]
@garrison-ball I wish, the best thing we have so far is another repository under this service-portal group. See https://github.com/service-portal/documentation

If you haven't yet, please also join the ServiceNow Developers slack channel, you can often find assistance with undocumented functionality there as well: http://snowslack.herokuapp.com/

**Comment by garrison-ball** [comment]
Thanks so much @assertivist! Very helpful.  I am a member already, but I hope other people will see this and join!

**Comment by patrickw14** [comment]
It implements a system called "long polling" (you can google that term for more info). Basically, we create a new HTTP request to the server, which the server essentially holds onto, and then resolves when it has something to post. It's a bit like WebSockets, but built on top of HTTP requests :)

In terms of performance, I can put it this way - we implemented systems like our simple list, Connect chat, Activity Stream, and Presence using RecordWatch. As long as the tables you watch aren't posting hundreds of updates a minute, you should be OK.

Of course, like all things, it depends on the implementation
