### ISSUE TITLE
Change Widget Options

### ISSUE THREAD

**Issue by t1mb0b** [service-portal/CCW3956#2]
Is it possible through the client or server code to change a value in the options schema? As an example, if I had a 'mode' boolean value I wanted to change in the widget (i.e read vs edit), can I set the option to false by default, then the user clicks a button, which sets the mode to true, thus allowing for the fields to be edited?

Thanks!

**Comment by assertivist** [comment]
What's your use case? I dunno if storing dynamic data on the widget instance is a good plan.

**Comment by t1mb0b** [comment]
Say I have a card, like in the example. I want to edit the data in the card. I can switch between edit and view mode using a boolean value. If I switch to edit mode, the fields become input fields as opposed to text in div tags.

Tim

**Comment by assertivist** [comment]
@t1mb0b You can have the "default" of the boolean in your options schema and then simply load that boolean in your controller. When you flip back and forth, there's no real need to sync that change to the options schema unless you want that change to persist after the widget is no longer on the page. Does that make sense?

**Comment by t1mb0b** [comment]
Yes, thanks!
